// ======================================================================
// Copyright (c) 2026 Waldemar Derr. All rights reserved.
//
// Licensed under the MIT license. See included LICENSE file for details.
// ======================================================================

unit Test.Includer;

interface

uses

  Winapi.Windows,

  System.Classes,
  System.IOUtils,
  System.SysUtils,

  DUnitX.TestFramework,

  TmplCodeGen.Common,
  TmplCodeGen.Includer,
  TmplCodeGen.Logger,
  TmplCodeGen.Utils,

  Test.Base,
  Test.Logger;

type

  [TestFixture]
  TTestTmplCodeGenIncluder = class(TTestBase)
  public
    [Test]
    procedure TestIncludePartials;
    [Test]
    procedure TestRetakeInterfaceGuids;
    [Test]
    procedure TestRemovePartialStmts;
  end;

implementation

{ TTestTmplCodeGenIncluder }

procedure TTestTmplCodeGenIncluder.TestIncludePartials;
var
  Content    : String;
  Includer   : TIncludePartials;
  PartialFile: String;
  TargetFile : String;
begin
  TargetFile := 'Target.pas';
  PartialFile := 'MyPartial.part.pas';

  TFile.WriteAllText(TargetFile, 
    '''
    unit Target;
    interface
    {$REGION 'INCLUDE-PARTIAL / MyPartial.part.pas'}
    // This content should be replaced
    {$ENDREGION 'INCLUDE-PARTIAL / MyPartial.part.pas'}
    implementation
    end.
    ''');

  TFile.WriteAllText(PartialFile,
    '''
    {$REGION 'DEFINE-PARTIAL / MyPartial'}
    type
      TMyClass = class
      end;
    {$ENDREGION 'DEFINE-PARTIAL / MyPartial'}
    ''');

  Includer := TIncludePartials.Create(TargetFile, FLogger);
  try
    Includer.Execute;
  finally
    Includer.Free;
  end;

  Content := TFile.ReadAllText(TargetFile);

  Assert.IsTrue(Content.Contains('type'), 'Partial content missing');
  Assert.IsTrue(Content.Contains('TMyClass = class'), 'Partial class missing');
  Assert.IsFalse(Content.Contains('// This content should be replaced'), 'Old content should be gone');
  Assert.IsFalse(Content.Contains('DEFINE-PARTIAL'), 'Define-Partial directives should be removed');
  Assert.IsTrue(Content.Contains('INCLUDE-PARTIAL'), 'Include-Partial directives should remain');
end;

procedure TTestTmplCodeGenIncluder.TestRetakeInterfaceGuids;
var
  Content    : String;
  Includer   : TIncludePartials;
  PartialFile: String;
  TargetFile : String;
begin
  TargetFile := 'TargetGuids.pas';
  PartialFile := 'PartialGuids.part.pas';

  // Target file has an existing interface with a specific GUID
  TFile.WriteAllText(TargetFile, '''
    unit TargetGuids;
    interface
    {$REGION 'INCLUDE-PARTIAL / PartialGuids.part.pas'}
    type
      IMyInterface = interface
        ['{11111111-1111-1111-1111-111111111111}']
      end;
    {$ENDREGION 'INCLUDE-PARTIAL / PartialGuids.part.pas'}
    implementation
    end.
    ''');

  // Partial file has the same interface but with a NEW GUID (generated by template)
  TFile.WriteAllText(PartialFile, '''
    type
      IMyInterface = interface
        ['{22222222-2222-2222-2222-222222222222}']
      end;
    ''');

  Includer := TIncludePartials.Create(TargetFile, FLogger);
  try
    Includer.Execute;
  finally
    Includer.Free;
  end;

  Content := TFile.ReadAllText(TargetFile);

  // We expect the ORIGINAL GUID (111...) to be preserved, not the new one (222...)
  Assert.IsTrue(Content.Contains('[''{11111111-1111-1111-1111-111111111111}'']'), 'Original GUID should be preserved');
  Assert.IsFalse(Content.Contains('[''{22222222-2222-2222-2222-222222222222}'']'), 'New GUID should be ignored');
end;

procedure TTestTmplCodeGenIncluder.TestRemovePartialStmts;
var
  Content: String;
  Result : String;
begin
  Content := '''
    Some Code
    {$REGION 'DEFINE-PARTIAL / MyParam'}
    More Code
    {$ENDREGION 'DEFINE-PARTIAL / MyParam'}
    End Code
    ''';

  Result := RemovePartialStmts(Content, ['DEFINE-PARTIAL']);

  Assert.IsFalse(Result.Contains('{$REGION'), 'REGION should be removed');
  Assert.IsFalse(Result.Contains('{$ENDREGION'), 'ENDREGION should be removed');
  Assert.IsTrue(Result.Contains('Some Code'), 'Content should remain');
  Assert.IsTrue(Result.Contains('More Code'), 'Inner content should remain');
end;

end.
