// START: STYLE-TEMPLATE===========================================================================// START: AI-Descriptions===========================================================================// Start: AI-Generated FitNesse-Test================================================================
// ======================================================================                          // - Jede Unit muss mit diesem Banner beginnen                                                      // |script|Dpt Lint Fixture|
//                                                                                                 //                                                                                                  // |Set Target File|${TargetFile}|
// AnyUnitName - Kurzbeschreibung der Unit                                                         // - Hier steht der Name der Unit, der gleich dem Unit-Namen sein muss.                             // |check|Unit Name Matches File Name|true|
//                                                                                                 //   Es sollte eine Kurzbeschreibung existieren.                                                    // |check|File Contains Include|Base.Define.pas;Tfw.Define.pas|true|
// Autor: Auflistung von Hauptverantwortlichen                                                     // - Es muss mindestens ein Hauptverantwortlicher vorhanden sein. Mehrere Autoren werden            // |check|Keyword|interface|Is Surrounded By|=======|true|
//                                                                                                 //   Mehrere Autoren werden mit "/" getrennt.                                                       // |$InterfacePart=|Get Interface Part|
// ======================================================================                          // - Hier endet der Banner                                                                          // |$InterfaceOffset=|Get Interface Part Offset|
                                                                                                   // - Obligatorische Leerzeile                                                                       // |$Header=|Get Before Unit Keyword Part|
{$I Tfw.Define.pas}                                                                                // - Es muss entweder eine "Base.Define.pas" oder "Tfw.Define.pas" included werden                  // |script|Dpt Lint Regex Fixture|$Header|
                                                                                                   // - Obligatorische Leerzeile                                                                       // |check|Match|(?s)// =+.*?// .*?Autor: .+?// =+|true|
unit AnyUnitName;                                                                                  //                                                                                                  //
                                                                                                   // - Obligatorische Leerzeile                                                                       // |script|Dpt Lint Uses Fixture|${TargetFile}|
{ ======================================================================= }                        // - Vor dem Interface-Keyword muss die doppelte Trennlinie stehen                                  // |Set Content|$InterfacePart|
interface                                                                                          //                                                                                                  // |Set Line Offset|$InterfaceOffset|
{ ======================================================================= }                        // - Nach dem Interface-Keyword muss die doppelte Trennlinie stehen                                 // |Add Group|Delphi|With Namespaces|System.*, Vcl.*, Winapi.*, Data.*, Xml.*, Web.*, Soap.*|
                                                                                                   // - Obligatorische Leerzeile vor "uses"                                                            // |Add Group|Third-Party|With Namespaces|*|
uses                                                                                               // - "uses" muss alleine in einer Zeile stehen                                                      // |Add Group|Base|With Namespaces|Base.*|
                                                                                                   // - Obligatorische Leerzeile nach "uses"                                                           // |Add Group|Base-UI|With Namespaces|Base.UI.*|
  System.SysUtils,                                                                                 // - Je Zeile darf nur eine Unit stehen                                                             // |Add Group|Business|With Namespaces|Business.*|
  Vcl.Controls,                                                                                    // - Alphabetische Auflistung von Delphi-Units in Gruppen:                                          // |Add Group|Shared|With Namespaces|*.Shared.*, Dms.Shared.*|
  Vcl.Forms,                                                                                       //   - Delphi-Gruppe:      System.*, Winapi.*, VCL.*                                                // |Add Group|TFW|With Namespaces|Tfw.*|
  Vcl.Graphics,                                                                                    //                                                                                                  // |check|All Units On Separate Lines|true|
  Winapi.Messages,                                                                                 //                                                                                                  // |check|Groups Follow Order|true|
                                                                                                   //   - Nach jeder Gruppe kommt eine Leerzeile                                                       // |check|Groups Are Sorted Alphabetically|true|
  Spring.Collections,                                                                              //   - Third-Party:        *                                                                        // |check|Groups Are Separated By Blank Lines|true|
  VirtualTrees,                                                                                    //                                                                                                  // |$LinesAfterUses=|Get Lines After Last Uses Line|3|
                                                                                                   //                                                                                                  // |$AfterUsesOffset=|Get Lines After Last Uses Line Offset|3|
  Base.Cmd,                                                                                        //   - Base-Gruppe:        Base.*                                                                   //
  Base.Utils.Msg,                                                                                  //                                                                                                  // |script|Dpt Lint Regex Fixture|$LinesAfterUses|
                                                                                                   //                                                                                                  // |Set Line Offset|$AfterUsesOffset|
  Base.UI.Icons,                                                                                   //   - Base-UI-Gruppe:     Base.UI.*                                                                // |check|Match|(?s)^\s*\r?\n\{ -+ \}\s*\r?\n\s*$|true|
                                                                                                   //                                                                                                  //
  Lib.Table,                                                                                       //                                                                                                  // |script|Dpt Lint Class Declaration Fixture|${TargetFile}|
  Lib.Types,                                                                                       //                                                                                                  // |Set Content|$InterfacePart|
                                                                                                   //                                                                                                  // |Set Line Offset|$InterfaceOffset|
  Business.Bank.Form,                                                                              //   - Business-Gruppe:    Business.*                                                               // |Set Class Name Prefixes|C,T|
                                                                                                   //                                                                                                  // |Set Visibility Extra Indent|1|
  Business.UI.Message,                                                                             //   - Business-UI-Gruppe: Business.*                                                               // |Set Field Name Prefix|F|
                                                                                                   //                                                                                                  // |Set Fields Must Be Sorted|true|
  Dms.Shared.App.Utils,                                                                            //   - Shared-Gruppe:      *.Shared.*                                                               // |Set Methods Must Be Sorted|true|
  Dms.Shared.Kw.Tree,                                                                              //                                                                                                  // |Set Properties Must Be Sorted|true|
                                                                                                   //                                                                                                  // |Set Align Member Names|true|
  Tfw.Ad.Typ,                                                                                      //   - TFW-Gruppe:         Tfw.*                                                                    // |check|Lint Class Declarations|true|
  Tfw.VBh.Typ;                                                                                     //                                                                                                  //
                                                                                                   // - Obligatorische Leerzeile nach der letzten Unit                                                 //
{ ----------------------------------------------------------------------- }                        // - Obligatorische einfache Trennlinie, die den Uses-Bereich optisch trennt                        //
                                                                                                   // - Obligatorische Leerzeile vor "type"                                                            //
type                                                                                               // - "type" muss alleine stehen                                                                     // |script|Dpt Lint Fixture|
                                                                                                   // - Obligatorische Leerzeile nach "type"                                                           // |Set Target File|${TargetFile}|
  TMyRecord = packed record                                                                        // - Namen von Records fangen immer mit "T" an                                                      // |check|Colons In Records Are Aligned|true|
    GUID          : TGUID;                                                                         // - Doppelpunkte sind vertikal untereinander ausgerichtet                                          //
    Var1          : Integer;                                                                       //                                                                                                  //
    Var2          : TDate;                                                                         //                                                                                                  //
    Filler1       : Array[1..300] of Byte;                                                         //                                                                                                  //
    case Byte of                                                                                   //                                                                                                  //
      0: (Filler2 : Array[1..4096] of Byte);                                                       //                                                                                                  //
      1: (Variant1: TMyVariant1);                                                                  //                                                                                                  //
      2: (Variant2: TMyVariant2);                                                                  //                                                                                                  //
  end;                                                                                             //                                                                                                  //
                                                                                                   //                                                                                                  //
  CSomeClass = class                                                                               // - Klassennamen sollten mit "C" anfangen, können aber auch klassisch mit "T" anfangen             //
   strict private                                                                                  // - Die Keywords für die Sichtbarkeit sind mit einem zusätzlichen Leerzeichen eingerückt           //
    FText: String;                                                                                 // - Feldnamen fangen mit einem "F" an                                                              //
    FValue: Word;                                                                                  // - Felder in einem zusammenhängenden Block sind alphabetisch sortiert                             //
    FVar: Integer;                                                                                 // - Hier müssen die Doppelpunkte NICHT untereinander stehen                                        //
    function  GetVar1: Integer;                                                                    // - Die Namen von Funktionen und Prozeduren im gleichen zusammenhängenden Block                    //
    procedure SetVar1(AValue: Integer);                                                            //   stehen untereinandner                                                                          //
   strict private class var                                                                        // - Die Keywords für die Sichtbarkeit leiten einen neuen Block ein                                 //
    FClassVar: String;                                                                             //                                                                                                  //
   strict protected                                                                                //                                                                                                  //
    procedure DoSomething;                                                                         // - Die Funktionen und Prozeduren in einem zusammenhängenden Block sind alphabetisch               //
    function  IsSomething: Boolean;                                                                //   nach Name sortiert                                                                             //
   public                                                                                          //                                                                                                  //
    constructor Create;                                                                            // - Konstruktoren und Destruktoren bilden eine eigene Gruppe (Ausrichtung gilt nur hier)           //
    destructor  Destroy; override;                                                                 //                                                                                                  //
    function  CalcValue: Word;                                                                     // - Die Namen von Prozeduren, Funktionen und Properties stehen im gleichen                         //
    procedure CalcVar1;                                                                            //   zusammenhängenden Block untereinander                                                          //
    property  Value: Word read FValue;                                                             // - Properties stehen am Ende eines Sichtbarkeits-Blocks und sind                                  //
    property  Var1: Integer read GetVar1 write SetVar1;                                            //   alphabetisch nach Name sortiert                                                                //
   public                                                                                          //                                                                                                  //
    class procedure Init;                                                                          // - Klassen-Methoden/Konstruktoren stehen in einem eigenen Sichtbarkeitsblock                      //
  end;                                                                                             //                                                                                                  //
                                                                                                   // - Obligatorische Leerzeile                                                                       //
{ ======================================================================= }                        // - Vor dem "implementation"-Keyword muss die doppelte Trennlinie stehen                           // |script|Dpt Lint Fixture|
implementation                                                                                     //                                                                                                  // |Set Target File|${TargetFile}|
{ ======================================================================= }                        // - Nach dem "implementation"-Keyword muss die doppelte Trennlinie stehen                          // |check|Keyword|implementation|Is Surrounded By|=======|true|