// ======================================================================
// Copyright (c) 2026 Waldemar Derr. All rights reserved.
//
// Licensed under the MIT license. See included LICENSE file for details.
// ======================================================================

program RsmDesk;

uses
  System.StartUpCopy,
  FMX.Forms,
  RsmDesk.MainForm in 'RsmDesk.MainForm.pas' {FormMain};

// The project .res (icon / version-info / High-DPI manifest) is
// generated by the build host from the .dproj settings -- it is
// gitignored and regenerated on every build. The {$R *.res} below links
// it; without it the Per-Monitor-V2 manifest would not be embedded and
// the app would run DPI-unaware (blurry, bitmap-stretched) on high-DPI
// monitors. See the Manifest_File / AppDPIAwarenessMode keys in
// RsmDesk.dproj.
{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
